### ISSUE TITLE
ESP32C3 Version

### ISSUE THREAD

**Issue by Soforak** [gjroots/esp32_nat_router_plus#25]
**Is your feature request related to a problem? Please describe.**
I tried to change the version to ESP32C3 but couldn't manage to get anything but errors

**Describe the solution you'd like**
Could you please upload a compiled version for the ESP32C3 please?

**Comment by gjroots** [comment]
Hi. @Soforak 

Currently i don't have suitable environment setup to build, please share error log may I can help if anything to possible. 
Surely i will share you firmware files as soon as possible.

**Comment by gjroots** [comment]
Hi @Soforak, can you please test the firmware and provide me with an update? Thanks!

[esp32C3.zip](https://github.com/user-attachments/files/17879928/esp32C3.zip)

**Comment by JacobsIntegralEdition** [comment]
Can u please make the esp32 c3 version for this?

**Comment by KalleAnka** [comment]
Hi, it works on a Shelly Mini 1 Gen 3. It uses a ESP32-C3 8MB.
Do you have the source code for this compilation?

**Comment by gjroots** [comment]
Hi, just add these and try to build [env:esp32-c3]

Shere me the result, the rest of code same

Check your device is jtag or usb or else get issue in cmd prompt. That's all,
[esp32c3.zip](https://github.com/user-attachments/files/20874144/esp32c3.zip)

**Comment by KalleAnka** [comment]
Hi,

Getting this while compiling:
```
Compiling .pio\build\esp32-c3\components\cmd_router\cmd_router.c.o
Compiling .pio\build\esp32-c3\components\cmd_system\cmd_system.c.o
Compiling .pio\build\esp32-c3\cmock\CMock\src\cmock.c.o
components\cmd_nvs\cmd_nvs.c: In function 'get_value_from_nvs':
components\cmd_nvs\cmd_nvs.c:295:22: error: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Werror=format=]
  295 |             printf("%d\n", value);
      |                     ~^     ~~~~~
      |                      |     |
      |                      int   int32_t {aka long int}
      |                     %ld
components\cmd_nvs\cmd_nvs.c:300:22: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  300 |             printf("%u\n", value);
      |                     ~^     ~~~~~
      |                      |     |
      |                      |     uint32_t {aka long unsigned int}
      |                      unsigned int
      |                     %lu
components\cmd_nvs\cmd_nvs.c: In function 'list':
components\cmd_nvs\cmd_nvs.c:377:25: error: too few arguments to function 'nvs_entry_find'
  377 |     nvs_iterator_t it = nvs_entry_find(part, NULL, type);
      |                         ^~~~~~~~~~~~~~
In file included from components\cmd_nvs\cmd_nvs.c:22:
C:\Users\Administrator\.platformio\packages\framework-espidf\components\nvs_flash\include/nvs.h:716:11: note: declared here
  716 | esp_err_t nvs_entry_find(const char *part_name,
      |           ^~~~~~~~~~~~~~
components\cmd_nvs\cmd_nvs.c:386:29: error: passing argument 1 of 'nvs_entry_next' from incompatible pointer type [-Wincompatible-pointer-types]
  386 |         it = nvs_entry_next(it);
      |                             ^~
      |                             |
      |                             nvs_iterator_t {aka struct nvs_opaque_iterator_t *}
C:\Users\Administrator\.platformio\packages\framework-espidf\components\nvs_flash\include/nvs.h:775:42: note: expected 'struct nvs_opaque_iterator_t **' but argument is of type 'nvs_iterator_t' {aka 'struct nvs_opaque_iterator_t *'}
  775 | esp_err_t nvs_entry_next(nvs_iterator_t *iterator);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~
components\cmd_nvs\cmd_nvs.c:386:12: error: assignment to 'nvs_iterator_t' {aka 'struct nvs_opaque_iterator_t *'} from 'esp_err_t' {aka 'int'} makes pointer from integer without a cast [-Wint-conversion]
  386 |         it = nvs_entry_next(it);
      |            ^
cc1.exe: some warnings being treated as errors
Compiling .pio\build\esp32-c3\console\commands.c.o
components\cmd_router\cmd_router.c:15:10: fatal error: esp_spi_flash.h: No such file or directory

***********************************************************************
* Looking for esp_spi_flash.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_spi_flash.h"
* Web  > https://registry.platformio.org/search?q=header:esp_spi_flash.h
*
***********************************************************************

   15 | #include "esp_spi_flash.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32-c3\components\cmd_nvs\cmd_nvs.c.o] Error 1
*** [.pio\build\esp32-c3\components\cmd_router\cmd_router.c.o] Error 1
In file included from components\cmd_system\cmd_system.c:17:
C:\Users\Administrator\.platformio\packages\framework-espidf\components\spi_flash\include/esp_spi_flash.h:6:2: warning: #warning esp_spi_flash.h is deprecated, please use spi_flash_mmap.h instead [-Wcpp]
    6 | #warning esp_spi_flash.h is deprecated, please use spi_flash_mmap.h instead
      |  ^~~~~~~
components\cmd_system\cmd_system.c:18:10: fatal error: driver/rtc_io.h: No such file or directory
   18 | #include "driver/rtc_io.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32-c3\components\cmd_system\cmd_system.c.o] Error 1
=================================================================================================================== [FAILED] Took 8.13 seconds ===================================================================================================================
Environment    Status    Duration
-------------  --------  ------------
esp32-c3       FAILED    00:00:08.135
============================================================================================================= 1 failed, 0 succeeded in 00:00:08.135 ============================================================================================================= 

```

What do you mean by: Check your device is jtag or usb or else get issue in cmd prompt
I am using VS Code.

**Comment by KalleAnka** [comment]
Forget info regarding the installed packages.
They might be different from yours.
Which ones do you have for the esp32-c3?

```
Processing esp32-c3 (platform: espressif32; board: esp32-c3-devkitm-1; framework: espidf)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c3-devkitm-1.html
PLATFORM: Espressif 32 (6.11.0) > Espressif ESP32-C3-DevKitM-1
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.50401.0 (5.4.1)
 - tool-cmake @ 3.16.4
 - tool-esp-rom-elfs @ 0.0.1+20241011
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-ninja @ 1.9.0
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208 
 - toolchain-esp32ulp @ 1.23800.240113 (2.38.0)
 - toolchain-riscv32-esp @ 14.2.0+20241119
```

**Comment by gjroots** [comment]
Just re-clone the repository and try once... I think it's old files not updated properly... Already fixed in last time.

**Comment by KalleAnka** [comment]
Hi, now I'm getting two problems:

Warning:
`C:/Ruby34-x64/lib/ruby/gems/3.4.0/gems/bundler-2.4.4/lib/bundler/definition.rb:524:in 'Bundler::Definition#materialize': Could not find google-protobuf-3.24.2-x64-mingw-ucrt in locally installed gems (Bundler::GemNotFound)`
Tried to install it via gem install google-protobuf -v 3.24.2. No problem with install. Restarted VS Code and same problem.

Error:
`Building in release mode
Compiling .pio\build\esp32dev\components\cmd_router\cmd_router.c.o
components/cmd_router/cmd_router.c:15:10: fatal error: spi_flash_mmap.h: No such file or directory
`
Do you know where to get the correct spi_flash_mmap.h file?
Maybe https://github.com/espressif/esp-idf/blob/master/components/spi_flash/include/spi_flash_mmap.h ?

Be advised that I am not yet running the ESP32-C3 compilation, just the standard in platformio.ini.

**Comment by KalleAnka** [comment]
Strange, already had spi_flash_mmap.h but the compiler was unable to find it.
Changed from relative path to absolute path:
```
//#include "spi_flash_mmap.h"
#include "c:\Users\Administrator\.platformio\packages\framework-espidf\components\spi_flash\include\spi_flash_mmap.h"

```
Now it compiles the C3 version. Upload of firmware.bin file works.
But the version does not change on the info page.
It still says 1.2.0 but I changed it to 1.2.1 in two places.
So I am uncertain if the OTA upload is committed to flash or if the HTML compiler fails.

**Comment by gjroots** [comment]
**Congratulations!**

Changing the version number in the web interface is a bit tricky.  

Normally, if you install Jekyll, the version is updated automatically by the script.  
But if you prefer a quick and manual method without full setup:

1. Unzip the file  
2. Open and edit the version string (e.g., `version=1.2.0`)  
   → File path: `components/web_server/www/output/gzip/functions.js.gz`  
3. Re-gzip the file

For more details, refer to the [build documentation](https://github.com/gjroots/esp32_nat_router_plus/blob/main/docs%2FBuild_setup.md).


> So I am uncertain if the OTA upload is committed to flash or if the HTML compiler fails.

Nothing will happen do what you think see what things are going...  Do your experiment

**Comment by KalleAnka** [comment]
Thank you for your quick help with the build.

Something was wrong with my build environment regarding Jekyll.
Had to Google to get it updated(forgot which command).
Afterwards I was still missing some components so they had to be added manually with:
`bundle add`

The Gemfile auto-updated with the following:
```
gem "csv", "~> 3.3"

gem "base64", "~> 0.3.0"

gem "bigdecimal", "~> 3.2"
```

Now the version number updated correctly in the web GUI.
Will start to play around for specific Shelly Mini 1 Gen 3 support:
* Flash size 8 MB.
* LED on GPIO 0.
* Button on GPIO 1.
* A problem if WPA password contains the # sign https://github.com/gjroots/esp32_nat_router_plus/issues/38
